apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jupyter-web-app-jupyter-web-app
  namespace: kubeflow
spec:
  hosts:
    - "deploykf.neor.ir"
  gateways:
    - deploykf-istio-gateway/deploykf-gateway
